[package]
name = "pokemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.12"
serde_json = "1.0.86"
wasm-bindgen-futures = "0.4.33"
web-sys = "0.3.60"
yew = "0.19.3"
